export const queryKeys = {
  appInfo: ["app-info"] as const,
  runtime: ["runtime"] as const,
  bootstrap: ["runtime", "bootstrap"] as const,
  status: ["runtime", "status"] as const,
  devices: ["runtime", "devices"] as const,
  conflicts: ["runtime", "conflicts"] as const,
  ipv6Network: ["runtime", "ipv6-network"] as const,
  history: ["runtime", "history"] as const,
  activity: ["runtime", "activity"] as const,
  monitoringSettings: ["runtime", "monitoring-settings"] as const,
  notificationSettings: ["runtime", "notification-settings"] as const,
  controlAudit: ["runtime", "control-audit"] as const,
  bandwidthLimits: ["runtime", "bandwidth-limits"] as const,
  bandwidthMonitors: ["runtime", "bandwidth-monitors"] as const,
  bandwidthMeasurements: ["runtime", "bandwidth-measurements"] as const,
  bandwidthHealth: ["runtime", "bandwidth-health"] as const,
  bandwidthHistory: (mac: string, range: string) => ["runtime", "bandwidth-history", mac, range] as const,
}
